version: '3.8'
services:
  keystore:
    build: ./
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '0.5'
    ports:
      - '127.0.0.1:5010:5010'
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: keystore
      MYSQL_DATABASE: keystore
      MYSQL_USER: keystore
      MYSQL_PASSWORD: keystore
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./data:/var/lib/mysql/