CREATE TABLE IF NOT EXISTS users (
    id MEDIUMINT PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS privkeys (
    id MEDIUMINT REFERENCES users(id),
    privkey VARCHAR(1024) NOT NULL
);